### ISSUE TITLE
detect indent

### ISSUE THREAD

**Issue by futurist** [panz3r/update-pkg-extended#1]
It's possible to detect indent of the package.json file, and use that instead of hardcoded indent of 4?

**Comment by panz3r** [comment]
Hi @futurist ,

Unfortunately that's actually not possible but when calling the `save` methods you can specify a custom indentation instead of the default `4`.

Let me know if this can help you.

**Comment by panz3r** [comment]
Hi @futurist ,

As of version 2.0, the feature you requested has been implemented.

Thanks for your feedback.
