### ISSUE TITLE
version patch not work for alpha/beta

### ISSUE THREAD

**Issue by futurist** [panz3r/update-pkg-extended#7]
When patch below version:

1.1.1-alpha

It not work

**Comment by panz3r** [comment]
Hi @futurist ,
Thanks for your feedback. 

Unfortunately at the moment the support for labels for `pre-release` and `build metadata` is not included in this module.
I'll try to add this feature soon.

**Comment by panz3r** [comment]
Support for prerelease version has been added.

Please update to version `2.1.0`.
